import { Center, Text } from "@mantine/core";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Next + Mantine + TypeScript</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Center>
        <Text>Mantine UI is so Cool</Text>
      </Center>
    </>
  );
}
